Add optional sku property to object storages
MaibornWolff/hybrid-cloud-object-storage-operator pull request #18
Opened 2023-11-20 10:56 UTC by BeTheFlow95

This PR adds the possibility to change the SKU type for each object-storage individually. Similar to setting the accessibility of object-storages

2023-11-20 10:58 UTC, lieberlois approved these changes
LGTM!

2023-11-20 12:04 UTC, swoehrl-mw requested changes
SKU is something Azure-specific and I want to avoid having anything provider-specific in the CRDs as that would break the abstraction.

Suggestion: Introduce the concept of classes similar to how the hybrid-cloud-postgresql-operator does it. These classes can then in the backend config be mapped to SKUs.

2023-11-20 13:55 UTC, lieberlois commented
@swoehrl-mw I agree that the wording "SKU" should be changed, however i dont think "classes" really make sense. It suggests that each cloud provider has the same amount of classes, which is not the case. IMO the value of the field can be vendor specific, since the "backend" field already discriminates between cloud providers. This is the same for "backup"

2023-11-20 14:31 UTC, swoehrl-mw commented
@lieberlois 

> It suggests that each cloud provider has the same amount of classes, which is not the case.

Not really. It puts the responsibility on the person configuring the operator and its backends to define classes that are available in all providers used in a platform or at least choose similar types.

>  since the "backend" field already discriminates between cloud providers. This is the same for "backup"

Normally the `backend` field should not be used, it is mainly there to allow choosing if several backends are available in one cluster. Nevertheless, the idea is still that users can just switch the backend or deploy to another cluster where the operator is configured with another default backend without changing any of the (other) fields. `backup` is not really specific, the operator could configure something equivalent for e.g. S3. As such I really don't want to have a field in there that the operator cannot automatically map between providers.

2023-11-23 09:00 UTC, lieberlois commented
@swoehrl-mw I see what you mean, I just thought this could minimize complexity. Looking at similar tools like Crossplane, the cleanest solution would probably be to add a CRD like "ProviderConfig" or so, that maps predefined classes to vendor-specific SKUs etc. For simplicity purposes, I would be fine with adding the mapping to the config aswell though

2023-11-23 12:02 UTC, swoehrl-mw requested changes

2023-11-23 12:02 UTC, swoehrl-mw commented on hybridcloud/backends/azureblob.py
> +
To stay compatible there should be a fallback (to `"Standard_LRS"`) if neither `sku.name` nor any classes or `default_class` are defined

2023-11-23 12:32 UTC, BeTheFlow95 commented on hybridcloud/backends/azureblob.py
> +    sku = config_get("backends.azureblob.sku.name")
Is changed here 
81508f256296ffafdae69b681c946888afbebb50

2023-11-23 12:32 UTC, BeTheFlow95 commented on hybridcloud/backends/azureblob.py
> +    classes = config_get("backends.azureblob.classes", default=[])
Is changed here 
81508f256296ffafdae69b681c946888afbebb50

2023-11-23 12:33 UTC, BeTheFlow95 commented on hybridcloud/backends/azureblob.py
> +
Adjusted the whole sku determination here.
81508f256296ffafdae69b681c946888afbebb50

2023-11-23 12:51 UTC, swoehrl-mw approved these changes

2023-11-23 12:53 UTC, merged