Adding option to use an Azure Backup Vault
MaibornWolff/hybrid-cloud-object-storage-operator pull request #2
Opened 2022-12-07 15:51 UTC by lieberlois

2022-12-14 12:05 UTC, swoehrl-mw requested changes

2022-12-19 09:35 UTC, lieberlois commented on README.md
> +      vault_name: foobar-vault  # The name of the existing backup vault, make sure the Storage Account has the Role Assignment "Storage Account Backup Contributor" for the according vault
You are right. I added a small paragraph that documents this.

2022-12-19 09:36 UTC, lieberlois commented on hybridcloud/backends/azureblob.py
> +                return (False, "Backup is enabled but vault_name and policy_name are not properly configured")
I adjusted the message accordingly

2022-12-19 09:37 UTC, lieberlois commented on hybridcloud/backends/azureblob.py
> +        storage_account = self._storage_client.storage_accounts.get_properties(self._resource_group, bucket_name)
I guess you are right. Future developers will have to take a good look here though! I moved it 👍

2022-12-19 09:53 UTC, lieberlois commented on hybridcloud/backends/azureblob.py
> +        if backup_enabled:
As discussed, i moved the logic into the validation logic

2022-12-19 09:53 UTC, lieberlois commented on hybridcloud/backends/azureblob.py
> +            vault_name = _backend_config("backup.vault_name", default="")
You are right, sir!

2022-12-22 07:25 UTC, swoehrl-mw approved these changes
LGTM

2022-12-22 07:26 UTC, merged