Adding latest-update field on custom object status
MaibornWolff/hybrid-cloud-object-storage-operator pull request #4
Opened 2022-12-28 16:41 UTC by lieberlois

During creation:
```yaml
status:
  backend: azureblob
  deployment:
    latest-update: "2022-12-28 17:37:00.870953"
    status: working
```

After creation:
```yaml
status:
  backend: azureblob
  deployment:
    latest-update: "2022-12-28 17:37:24.559091"
    reason: Bucket created
    status: finished
```

2023-01-11 11:35 UTC, swoehrl-mw requested changes

2023-01-11 11:35 UTC, swoehrl-mw commented on hybridcloud/handlers/bucket.py
> +        "latest-update": str(datetime.now())
Better to use a UTC timestamp to avoid timezone confusion. 
Recommende way in python is: `datetime.now(tz=timezone.utc).isoformat()`

2023-01-11 11:35 UTC, swoehrl-mw commented on hybridcloud/handlers/bucket.py
> +from datetime import datetime
Nitpick: Order of imports should be: std library, external libraries, own module.

2023-01-25 14:34 UTC, lieberlois commented
Adjusted as requested :)

2023-01-27 14:01 UTC, merged