Calling bucket_spec_valid in a k8s validating webhook
MaibornWolff/hybrid-cloud-object-storage-operator pull request #5
Opened 2022-12-28 17:11 UTC by lieberlois

This PR leverages the K8s native [dynamic admission controllers](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/) to run the function `bucket_spec_valid` in a validating webhook. This causes invalid specs to actually fail whereas until now invalid specs would only cause an error in the status.

In this example, the spec was invalid due to a name that was longer than 24 characters. The screenshot shows that the info generated by the `bucket_spec_valid` method is passed along to the user in the the form of a [kopf.AdmissionError](https://kopf.readthedocs.io/en/stable/admission/#validation-handlers)

<img width="1036" alt="image" src="https://user-images.githubusercontent.com/25712873/209847038-3202a833-cf95-4906-a50e-5b590813cfb9.png">

Once this PR is approved, I will do the same thing for the other `hybrid-cloud`-operators

2023-01-11 11:55 UTC, swoehrl-mw requested changes
A little explanation in the README is also missing.

2023-01-11 11:55 UTC, swoehrl-mw commented on README.md
> +2. Install dependencies: `pip install -r requirements.txt`. During development the additional command `pip install 'kopf[dev]'` is required (but not for production, so it is not part of requirements.
Did not test it yet, but if I read the kopf docs right, isn't `dev` also needed if we want automatically-generated certs for the webhook in production?
Size is not a problem, the azure sdk is quite big already so a bit more doesn't really matter.

2023-01-11 11:55 UTC, swoehrl-mw commented on hybridcloud/operator.py
> +    if os.environ.get('ENVIRONMENT') is None:
The else branch to configure admission when not developing is missing.
Also for detecting if we are running in a cluster, the existence of the `KUBERNETES_POD_NAME` envvar is a good test as we set that in the helm chart for the dpeloyment.

2023-01-11 11:55 UTC, swoehrl-mw commented on hybridcloud/operator.py
> +    settings.admission.managed = 'auto.kopf.dev'
To show the validation is coming from the operator it would be better to use something like `hybridcloud.maibornwolff.de` here.

2023-01-25 13:02 UTC, lieberlois commented on README.md
> +2. Install dependencies: `pip install -r requirements.txt`. During development the additional command `pip install 'kopf[dev]'` is required (but not for production, so it is not part of requirements.
Got it, including it in the requirements.txt

2023-01-25 13:03 UTC, lieberlois commented on hybridcloud/operator.py
> +    if os.environ.get('ENVIRONMENT') is None:
As discussed, using `kopf.WebhookAutoServer()` for now

2023-01-25 13:03 UTC, lieberlois commented on hybridcloud/operator.py
> +    settings.admission.managed = 'auto.kopf.dev'
Got it 👍

2023-01-25 14:31 UTC, lieberlois commented
Doesnt work yet, ServiceAccount doesn't seem to have enough permissions.

2025-01-28 14:04 UTC, swoehrl-mw commented
Closing as outdated

2025-01-28 14:04 UTC, closed without merging